name: "projet_elt_beneficiaire"
version: "1.0.0"
config-version: 2

profile: "projet_elt_beneficiaire"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  projet_elt_beneficiaire:
    silver:
      +materialized: table
      +schema: Silver
    gold:
      +materialized: table
      +schema: Gold
